### ISSUE TITLE
Stuck, unable to show subthreads?

### ISSUE THREAD

**Issue by alphapapa** [paul-issartel/nnreddit#3]
Hi again,

Not sure what I did, but now when I open the `nnreddit:emacs` summary buffer, all stories are displayed without comments.  Even when I mark them as unread, and even when I insert old articles with `/ o`, I can't see comments by pressing `RET` in the summary buffer.

I'm not sure, but I might have accidentally used `catchup-and-exit` on the summary buffer.  I thought that if I inserted old articles and marked them as unread, it would let me view their comments again, but this doesn't seem to work.  So it seems to be stuck.  :)

BTW, I don't know if you're interested in maintaining this, and I just posted three issues, so if you're not, it's okay.  But if you are, then I'll be glad to help test and debug.  It looks very promising so far!

Thanks.

**Comment by paul-issartel** [comment]
You need to add a `(display 'all)` parameter to the nnreddit group, because comments articles are generated as "old" due to a limitation (and can't be fetched through `/ o`).

As for maintenance, working on this is always fun and I'm glad that other people are using my code. But I'm going to be pretty busy in the next months, so I can't guarantee anything!

**Comment by alphapapa** [comment]
Thanks.  :)

**Comment by paul-issartel** [comment]
I really should add a notice somewhere (e.g. in the readme) because this problem can make the whole thing appear unusable.
